# Verify an installer against the SHA-256 companion generated by CI.
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$InstallerPath,
    [Parameter(Mandatory)]
    [string]$ChecksumPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $InstallerPath -PathType Leaf)) {
    throw "Installer was not found: $InstallerPath"
}
if (-not (Test-Path -LiteralPath $ChecksumPath -PathType Leaf)) {
    throw "Checksum file was not found: $ChecksumPath"
}

$installer = Get-Item -LiteralPath $InstallerPath
$manifest = (Get-Content -LiteralPath $ChecksumPath -Raw).Trim()
$entry = [regex]::Match($manifest, '^(?<hash>[A-Fa-f0-9]{64}) \*(?<file>.+)$')
if (-not $entry.Success) {
    throw 'Checksum file must contain one SHA-256 line in the form: <hash> *<installer-name>'
}

$expectedFileName = $entry.Groups['file'].Value
if (-not [string]::Equals($installer.Name, $expectedFileName, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Checksum belongs to $expectedFileName, not $($installer.Name)."
}

$expectedHash = $entry.Groups['hash'].Value.ToLowerInvariant()
$actualHash = (Get-FileHash -LiteralPath $installer.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
if ($actualHash -ne $expectedHash) {
    throw "SHA-256 mismatch for $($installer.Name). Expected $expectedHash, got $actualHash."
}

[pscustomobject][ordered]@{
    InstallerPath = $installer.FullName
    InstallerSize = $installer.Length
    Sha256        = $actualHash
    Verified      = $true
}
